// <auto-generated />
using HrPortal.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HrPortal.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HrPortalDbContext))]
    [Migration("20260705150000_AddTimeTrackingSchema")]
    partial class AddTimeTrackingSchema
    {
    }
}
